# Generated by Django 3.2 on 2021-04-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('entry_date', models.DateField(blank=True, default=1)),
                ('add_or_remove', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('Outro', 'Outro'), ('Trabalho', 'Trabalho'), ('Lazer', 'Lazer'), ('Aluguel', 'Aluguel'), ('Gastos Pessoais', 'Gastos Pessoais'), ('Investimentos', 'Investimentos')], max_length=50)),
                ('payment_type', models.CharField(choices=[('Dinehrio', 'Dinehrio'), ('Cartão', 'Cartão'), ('Cheque', 'Cheque'), ('Outro', 'Outro')], max_length=50)),
            ],
        ),
    ]
