# Generated by Django 3.2 on 2021-04-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_out', '0002_money_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='payment_type',
            field=models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão', 'Cartão'), ('Cheque', 'Cheque'), ('Outro', 'Outro')], max_length=50),
        ),
    ]
