# Generated by Django 3.2 on 2021-04-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_out', '0003_alter_money_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='obs',
            field=models.TextField(blank=True, max_length=80),
        ),
    ]
